### ISSUE TITLE
Initialise non-emtpy caches

### ISSUE THREAD

**Issue by kknehra** [graphaware/neo4j-importer#4]
Hello GraphAware,

I have created a cache that I would like to use in the following importer class.

```java
public class SubImporter extends BaseImporter<Label, MySqlDataReader> {

    @InjectCache(name = "testName", creator = true)
    private Cache<Long, Long> testCache;
```

However, for this specific cache, I would like to initialise it with some data before calling the `produceObject` and `processObject` methods. My reasoning is that I would like to create some nodes on-the-fly rather than specifically importing them.

The overridden `createCache` method in the `SubImporter` class, as follows, enables the cache to be initialised.

```java
@Override
protected void createCache(Caches caches, String name) {
    if ("testName".equals(name)) {
        caches.createCache(name, Long.class, Long.class);
    }
}
```

However the following excerpt of the `final` code in the `BaseImporter` class creates each cache in a `for` loop and then injects them into the importer afterwards.

```java
@Override
    public final void prepare(ImportContext importContext) {
    ....
    for (String cacheName : context.caches().createdCaches(this)) {
        createCache(context.caches(), cacheName);
    }
    context.caches().inject(this);
    ....
}
```

Given that this is the case, how can one then insert data into the cache (as follows) in any other method in the class **before** the `processObject` and `produceObject` methods begin.

```java
testCache.put(
    nodeId,
    context.inserter().createNode(
        new Label("Test").getProperties(),
        Label.label("TestLabel")
    )
);
```

Writing the previous code in the constructor or even in the `createCache` method in the `SubImporter` class of course will return a `NullPointerException` due to the way that the cache is initialised.

Does the `BaseImporter` `prepare` method need amending to allow this or is there a better way of doing it?

**Comment by kknehra** [comment]
Perhaps one solution could be adding an `initCaches` method.

```java
@Override
    public final void prepare(ImportContext importContext) {
    ....
    for (String cacheName : context.caches().createdCaches(this)) {
        createCache(context.caches(), cacheName);
    }
    initCaches();
    context.caches().inject(this);
    ....
}
```

The overridable method could be placed in `BaseImporter`.

```java
protected abstract void initCaches();
```

In `SubImporter` this could be implemented as follows.

```java
@Override
public void initCaches() {
    testCache.put(
    nodeId,
    context.inserter().createNode(
            new Label("Test").getProperties(),
            Label.label("TestLabel")
        )
    );
}
```

**Comment by bachmanm** [comment]
how about this?

**Comment by kknehra** [comment]
Works like a charm! 💯
